[theme]
primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#222222"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#000000"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true